### ISSUE TITLE
How to disable sorting for perticular colum?

### ISSUE THREAD

**Issue by himmatdb** [pguso/bootstrap-data-table#1]
Can you tell me how to disable sorting for perticular colum?

**Comment by johanneshorakjambit** [comment]
Depending on the Version you use  http://legacy.datatables.net/usage/columns#bSortable or https://datatables.net/reference/option/columns.orderable should answer your Question.

**Comment by pguso** [comment]
Added this functionality just add the css class disable-sorting to the colums where you want to disable sorting like this

```
 <th class="disable-sorting">#ID</th>
```
