### ISSUE TITLE
Data table limit

### ISSUE THREAD

**Issue by Kriptonium** [pguso/bootstrap-data-table#3]
Hi there! I have more than 600 row record on my table without using BDT. But when I use you BDT, my  last page was on page 107 only (with 5 record per page).

Are this code are limited to a certain record of row? It suppose to shows more than 600 rows.

**Comment by pguso** [comment]
Hey i tested it with the table generator from http://www.textfixer.com/html/html-table-generator.php with 599 rows and all rows show up no matter how many entries per page i choose. If you can be more specific reopen this ticket.
